import React,{useEffect,useState} from 'react';
import { curveLabel,PLOT_FONTS,CURVES,CURVE_LABELS,fullPlotView,validatePlotSnapshot,type PlotSnapshot,type PlotDesign,type CurveStyle } from '../../../shared/plot';
import { InteractivePlot,LegendControls } from './RefinementPlot';

const input='block w-full rounded border border-[#aeb8c2] bg-white px-2 py-1';
export default function PlotExportWindow(){
  const [tab,setTab]=useState('Size & file');
  const [selectedCurve,setSelectedCurve]=useState<typeof CURVES[number]>('observed');
  const [snapshot,setSnapshot]=useState<PlotSnapshot>();
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{window.cifApi.getPlotExport().then(value=>{setSnapshot(value);if(value.design.simulatedPattern)setSelectedCurve('calculated');}).catch(e=>setError(String(e)));document.title='Export Plot — CIF Crystal Data';},[]);
  if(!snapshot)return <main className="p-5">{error||'Loading plot…'}</main>;
  const {frame,design,view}=snapshot;
  const availableCurves=design.simulatedPattern?CURVES.filter(k=>k==='calculated'||k==='observed'&&!!frame.experimentalProfile?.length):CURVES;
  const change=(next:PlotDesign)=>setSnapshot({...snapshot,design:next});
  const number=(label:string,key:'width'|'height'|'dpi'|'fontSize'|'xInterval'|'xIntermediateLabels'|'axisFontSize'|'tickFontSize'|'legendFontSize'|'xMinorTicks'|'yMinorTicks'|'statisticsFontSize',min:number,max:number)=><label>{label}<input aria-label={label} className={input} type="number" min={min} max={max} step={key==='dpi'||key==='xIntermediateLabels'?1:'any'} value={Number.isNaN(design[key])?'':design[key]??(key==='xInterval'?10:key.endsWith('FontSize')?design.fontSize:0)} onChange={e=>change({...design,[key]:e.target.valueAsNumber})}/></label>;
  const fontSelect=(label:string,key:'axisFont'|'tickFont'|'legendFont'|'statisticsFont')=><label className="block text-xs">{label}<select aria-label={label} size={4} className="export-font-list" value={design[key]??'Arial'} onChange={e=>change({...design,[key]:e.target.value})}>{PLOT_FONTS.map(font=><option key={font} style={{fontFamily:font}}>{font}</option>)}</select></label>;
  const safePreview=Number.isFinite(design.width)&&design.width>=4&&Number.isFinite(design.height)&&design.height>=3&&Number.isFinite(design.fontSize)&&design.fontSize>=8;
  const curve=(k:typeof CURVES[number],patch:Partial<CurveStyle>)=>change({...design,curves:{...design.curves,[k]:{...design.curves[k],...patch}}});
  return <main className="plot-export-window bg-mica p-2 text-sm text-[#33475b]"><header className="export-heading flex items-center justify-between"><div><h1 className="text-base font-semibold">Export Plot</h1><p className="text-xs">Customize this snapshot. Changes here do not alter the refinement.</p></div><button className="btn-w32 btn-primary px-4 py-1" disabled={busy} onClick={async()=>{setError('');setMessage('');try{validatePlotSnapshot(snapshot);setBusy(true);const result=await window.cifApi.savePlotExport(design,view);if(result)setMessage('Saved: '+result);}catch(e){setError(String(e));}finally{setBusy(false);}}}>{busy?'Exporting…':'Save plot…'}</button></header>
    <div className="plot-export-layout"><aside className="plot-export-controls rounded border border-stroke bg-white"><div className="export-settings-tabs" role="tablist" aria-label="Plot settings">{['Size & file','Axes','Fonts','Ticks','Curves','Legend',...(design.simulatedPattern?[]:['Statistics'])].map(name=><button type="button" role="tab" id={'export-tab-'+name} aria-controls={'export-panel-'+name} aria-selected={tab===name} key={name} onClick={()=>setTab(name)}>{name}</button>)}</div><div className="export-settings-body"><section role="tabpanel" id="export-panel-Size & file" aria-labelledby="export-tab-Size & file" hidden={tab!=='Size & file'}><div className="grid grid-cols-2 gap-2 text-xs">{number('Width (inches)','width',4,24)}{number('Height (inches)','height',3,18)}{number('Resolution (dpi)','dpi',72,1200)}<label>Format<select aria-label="Export format" className={input} value={design.format} onChange={e=>change({...design,format:e.target.value as PlotDesign['format']})}><option value="png">PNG</option><option value="jpg">JPG</option><option value="tiff">TIFF</option><option value="svg">SVG (vector)</option><option value="pdf">PDF (vector)</option><option value="csv">CSV (data)</option></select></label>{number('Title font size','fontSize',8,24)}</div>
    <p className="text-xs">{design.format==='csv'?'Exports all snapshot data at its original intensity scale. Bragg Refelctions contains an independent list of exact reflection angles; blank cells pad the shorter list. Plot styling and zoom do not affect CSV.':['svg','pdf'].includes(design.format)?'Vector output remains sharp at any scale; dpi does not change vector detail.':`${Math.round(design.width*design.dpi)} × ${Math.round(design.height*design.dpi)} pixels. Maximum 40 megapixels.`}</p>
    </section><section role="tabpanel" id="export-panel-Axes" aria-labelledby="export-tab-Axes" hidden={tab!=='Axes'}>{(['title','xLabel','yLabel'] as const).map((key,i)=><label className="block text-xs" key={key}>{['Title','Horizontal axis label','Intensity axis label'][i]}<input className={input} maxLength={120} value={design[key]} onChange={e=>change({...design,[key]:e.target.value})}/></label>)}
    <div className="flex flex-wrap gap-2 text-xs"><label><input aria-label="Show Y-axis numbers" type="checkbox" checked={design.showYNumbers!==false} onChange={e=>change({...design,showYNumbers:e.target.checked})}/> Show Y-axis numbers</label><label><input aria-label="Enclose plot area" type="checkbox" checked={Boolean(design.enclosePlot)} onChange={e=>change({...design,enclosePlot:e.target.checked})}/> Enclose plot area</label></div>
    </section><section role="tabpanel" id="export-panel-Fonts" aria-labelledby="export-tab-Fonts" hidden={tab!=='Fonts'}><div className="grid grid-cols-2 gap-2 text-xs"><div>{fontSelect('Axis title font','axisFont')}{number('Axis title size','axisFontSize',8,32)}</div><div>{fontSelect('Tick number font','tickFont')}{number('Tick number size','tickFontSize',8,32)}</div></div><p className="text-xs">X and Y titles share one style; all axis numbers share the other. Unavailable fonts use the system fallback.</p>
    </section><section role="tabpanel" id="export-panel-Ticks" aria-labelledby="export-tab-Ticks" hidden={tab!=='Ticks'}>    <h2 className="font-semibold">X axis ticks</h2><div className="grid grid-cols-2 gap-2 text-xs">{number('Major interval (°)','xInterval',.000001,1000000)}{number('Labels between majors','xIntermediateLabels',0,20)}</div><p className="text-xs">Default: 10, 20, 30… With interval 10 and one label between majors: 10, 15, 20, 25…</p>
<div className="grid grid-cols-2 gap-2 text-xs">{number('X minor ticks','xMinorTicks',0,9)}{number('Y minor ticks','yMinorTicks',0,9)}</div><p className="text-xs">Unlabelled ticks between adjacent numbers. Zero removes minor ticks.</p>    </section><section role="tabpanel" id="export-panel-Curves" aria-labelledby="export-tab-Curves" hidden={tab!=='Curves'}><label className="block text-xs">Curve<select aria-label="Curve to customize" className={input} value={selectedCurve} onChange={e=>setSelectedCurve(e.target.value as typeof selectedCurve)}>{availableCurves.map(k=><option key={k} value={k}>{curveLabel(design,k)}</option>)}</select></label>{availableCurves.map(k=><fieldset hidden={selectedCurve!==k} className="rounded border p-2 text-xs" key={k}><legend className="px-1 font-semibold">{curveLabel(design,k)}</legend><div className="grid grid-cols-2 gap-2"><label>Color<input aria-label={`${k} color`} type="color" className="block h-8 w-full" value={design.curves[k].color} onChange={e=>curve(k,{color:e.target.value})}/></label><label>Style<select aria-label={`${k} style`} className={input} value={design.curves[k].mode} onChange={e=>curve(k,{mode:e.target.value as CurveStyle['mode']})}><option value="line">Line</option><option value="scatter">Scatter (circles)</option>{k==='reflections'&&<option value="ticks">Reflection ticks</option>}</select></label><label>{design.curves[k].mode==='scatter'?'Circle thickness':'Line thickness'}<input className={input} type="number" min="0.1" max="8" step="0.1" value={design.curves[k].width} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))curve(k,{width:e.target.valueAsNumber});}}/></label>{design.curves[k].mode==='scatter'&&<label>Circle diameter<input className={input} type="number" min="1" max="20" step="0.1" value={design.curves[k].size} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))curve(k,{size:e.target.valueAsNumber});}}/></label>}</div><label className="mt-2 block"><input type="checkbox" checked={design.curves[k].visible} onChange={e=>curve(k,{visible:e.target.checked})}/> Show curve</label></fieldset>)}
    </section><section role="tabpanel" id="export-panel-Legend" aria-labelledby="export-tab-Legend" hidden={tab!=='Legend'}><p className="text-xs">Drag the legend group in the preview to reposition it. Choose which entries to include below.</p><div className="grid grid-cols-2 gap-2 text-xs">{fontSelect('Legend font','legendFont')}{number('Legend font size','legendFontSize',8,32)}</div><LegendControls expanded design={design} setDesign={change}/></section><section role="tabpanel" id="export-panel-Statistics" aria-labelledby="export-tab-Statistics" hidden={tab!=='Statistics'}><label className="text-xs"><input type="checkbox" aria-label="Show fit statistics" checked={Boolean(design.showStatistics)} onChange={e=>change({...design,showStatistics:e.target.checked})}/> Show R<sub>p</sub>, R<sub>wp</sub> and GoF</label><div className="grid grid-cols-2 gap-2 text-xs">{fontSelect('Statistics font','statisticsFont')}{number('Statistics font size','statisticsFontSize',8,32)}</div><p className="text-xs">Drag the statistics group in the preview to move it independently of the curve legend. Unavailable values appear as a dash.</p></section></div></aside>
    <section className="plot-export-preview"><div className="flex flex-wrap gap-3 text-xs"><button className="btn-w32 px-3" onClick={()=>setSnapshot({...snapshot,view:design.simulatedPattern?{x:[...frame.range],y:[0,100],difference:[-1,1]}:fullPlotView(frame)})}>Full pattern</button><span>Fixed preview. Drag legend or statistics to reposition.</span></div><div className="plot-export-stage">{safePreview?<InteractivePlot legendOnly frame={frame} design={design} setDesign={change} view={view} setView={()=>undefined}/>:<p>Enter valid dimensions to preview.</p>}</div><p className="text-xs">Preview fits this area. Export uses your chosen dimensions and resolution.</p>{error&&<p role="alert" className="break-all text-red-700">{error}</p>}{message&&<p role="status" className="break-all">{message}</p>}</section></div>
  </main>;
}
